// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbWjbDcZWi-KxneeLbNwkgio_gdLaEh-E',
    appId: '1:645911289343:web:8c81e7bf1b4cc8ab4bdbca',
    messagingSenderId: '645911289343',
    projectId: 'salas-chat',
    authDomain: 'salas-chat.firebaseapp.com',
    storageBucket: 'salas-chat.firebasestorage.app',
    measurementId: 'G-K8046ZTTXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqKmhMheuT6C_y_rnShWTxaqMPLDkTdlg',
    appId: '1:645911289343:android:aa6d7531c6ee373b4bdbca',
    messagingSenderId: '645911289343',
    projectId: 'salas-chat',
    storageBucket: 'salas-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTlayn2-o9yTpw88cXWeZI1jPG9zrXTI',
    appId: '1:645911289343:ios:712099895287fc2f4bdbca',
    messagingSenderId: '645911289343',
    projectId: 'salas-chat',
    storageBucket: 'salas-chat.firebasestorage.app',
    iosBundleId: 'com.linikerthiers.salaschatfirebaseapp.salasChatFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTlayn2-o9yTpw88cXWeZI1jPG9zrXTI',
    appId: '1:645911289343:ios:712099895287fc2f4bdbca',
    messagingSenderId: '645911289343',
    projectId: 'salas-chat',
    storageBucket: 'salas-chat.firebasestorage.app',
    iosBundleId: 'com.linikerthiers.salaschatfirebaseapp.salasChatFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbWjbDcZWi-KxneeLbNwkgio_gdLaEh-E',
    appId: '1:645911289343:web:356ec9e13337fb3a4bdbca',
    messagingSenderId: '645911289343',
    projectId: 'salas-chat',
    authDomain: 'salas-chat.firebaseapp.com',
    storageBucket: 'salas-chat.firebasestorage.app',
    measurementId: 'G-0EQF8L009N',
  );

}